global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'jenkins-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['45.138.158.89:8765']  # Spring Boot port
