spring:
  application:
    name: jenkins

server:
  port: 8765
  shutdown: graceful
  servlet:
    context-path: "/jenkins"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs           # backend API docs path
  swagger-ui:
    enabled: true
    path: /swagger-ui            # Swagger UI path
    url: /v3/api-docs
